#!/usr/bin/perl --
use strict;
use warnings;

#
#
# need to know how many vcenter managerd on specific avamar server
#
#

use Net::OpenSSH;

my $user = 'admin';
my $password = 'AAbbccddee11!!';
my @avamarList = (#'a4dpe303.asl.lab.emc.com',

               'a4dpn226d3.asl.lab.emc.com',
               'a4dpn226d4.asl.lab.emc.com',
               'a3dpe262.asl.lab.emc.com',
               'ave1.virtualqa.com',
               'ave2.virtualqa.com',
               'ave3.virtualqa.com',
               'ave4.virtualqa.com',
               'ave6.virtualqa.com',

               #'dpe113.asl.lab.emc.com',
              );

foreach my $server (@avamarList){
    print "Server $server manage:\n";
    my $ssh = Net::OpenSSH->new("$user\@$server",password=>$password) ;
    $ssh->error and die "Could not establish ssh connection: " . $ssh->error;
    my @output = $ssh->capture('mcserver.sh --status | grep "^vCenter"');
    print "@output\n";
    chomp(@output);
    foreach my $vcenter (@output) {
        print "$vcenter\n";
    }
}
